--DROP TABLE IF EXISTS nyheter;

CREATE TABLE IF NOT EXISTS nyheter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tittel TEXT NOT NULL,
  nyhet TEXT NOT NULL,
  forfatter_id INTEGER NOT NULL
);

--DROP TABLE IF EXISTS brukere;
CREATE TABLE IF NOT EXISTS brukere (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Navn TEXT NOT NULL
);
